env:
  node: true
  es6: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: 
  no-console: 0 #not actuality for node
  import/extensions: 0 #the ability to add files with the extension
